config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root                  'static_pages#home'
  get     'home'    =>  'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  post    'sheet_change' => 'static_pages#sheet_change'
  get     'get_new_tab'  => 'static_pages#get_new_tab'
  post    'set_screen_size' => 'static_pages#set_screen_size'
  resources :users
  resources :tabs
  resources :sheets

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @page_data = page_data

  end

  def about
  end

  def sheet_change
    set_active_sheet params[:selected_value].to_i
    render :text => "success"
  end

  def get_sheet
    render :text=> "success"
    return current_sheet.id.to_i
  end

  def get_new_tab
    @last_tab = active_sheet.tabs.order(:created_at).first

    render :json => {
      name: @last_tab.name,
      address: @last_tab.address,
      picture: @last_tab.picture.url
    }

  end
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  

end

app/views/static_pages/about.html.erb
<%= provide(:title, 'About') %>
<%= stylesheet_link_tag "about" %>
<!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Tab Saver</h1>
                        <h3>An alternative to bookmarks</h3>
                        <hr class="intro-divider">
                        <%= link_to "Sign Up", signup_path, class: "btn btn-lrg btn-primary signup-button" %>
                        <%= link_to "Log In", login_path, class: "btn btn-lrg btn-primary "%>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">All of your links in one place:<br>easy to find</h2>
                    <p class="lead">A costomizable design that helps you quickly get to where you want to be.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                	<%= image_tag "TabSample.png", class: "img-responsive" %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Keep work and home seperate</h2>
                    <p class="lead">Use tabs to seperate your links into different categories</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                	<%= image_tag "tabs.png", class: "img-responsive" %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Our Mission</h2>
                    <p class="lead">We believe all the content you enjoy should be easy to organize and find. We want you to be able to pick up where you left off on your projects wherever you go by making it easy to save all your tabs in the cloud.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                	<%= image_tag "workEasy.png", class: "img-responsive" %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

app/views/static_pages/home.html.erb
<%= stylesheet_link_tag "def_home_box" %>
<% if logged_in? %>
<%= provide(:title, current_user.name + "'s links")%>

<% if get_screen_type == 0 %>
<div class="container">
	<div class="row">
		<div class="col-md-1 ops-area">
			<button type="button" id="add-button" data-toggle="modal" data-toggle="tooltip" data-target="#newTabModal" data-placement="left" title="New Link">
				<%= image_tag "newLink.png", size: "40x40", class: "ops-img" %>
			</button>

			<button class="ops-btns" id="delete-button"  data-toggle="tooltip" data-placement="right" title="Edit Links" onclick="location.href='<%= edit_user_path current_user %>'">
				<%= image_tag "editLink.png", size: "40x40", class: "ops-img" %>
			</button>
		</div>
		<div class="col-md-11">
			<%= render 'sheets/sheet_area'  %>
		</div>
	</div>
</div>

<% else %>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 mobile-ops">
			
			
				<button type="button" id="mobile-add-button" data-toggle="modal" data-target="#newTabModal" title="New Link">
					New Link
				</button>
		
			
				<button class="ops-btns" id="mobile-delete-button" title="Edit Links" onclick="location.href='<%= edit_user_path current_user %>'">
					Edit Links
				</button>
		
			
		</div>
		<div class="col-sm-12 mobile-sheetaria">
			<%= render 'sheets/sheet_area'  %>
		</div>
	</div>
</div>

<% end %>

<%= render 'layouts/newTabModal' %>

<script type="text/javascript">
	$(document).ready(function() {

		// Select first tab
		var $first_tab = $('#tabSheet a:first');
		$first_tab.tab('show');
		var tab_sheet = $first_tab.attr('id');
		$.post("/sheet_change", {
			selected_value : tab_sheet
		});

		// Update active tabe, and fix picture display
		$('#tabSheet a').click(function(e) {
			e.preventDefault()
			$(this).tab('show')
			var sheet = $(this).attr('id');
			$.post("/sheet_change", {
				selected_value : sheet
			});

			$(".tab_pic").each(function() {
				var title_height = $(".box-title").height();
				var inner_height = $(".box-inner").height();

				var box_width = $(".box-inner").width();
				var pic_width = $(this).width();
				var pic_height = $(this).height();
				var wid_diff = ((box_width - pic_width) / 2);
				var hit_diff = ((inner_height - pic_height) / 2);

				//var hit_diff = 0;
				$(this).css("left", wid_diff.toString() + "px");
				$(this).css("top", hit_diff.toString() + "px");

				var pos = $(this).position();
				if (pos.left < -50) {
					var h_dif = ($('.box-inner').height() - $(this).height()) * 0.5;
				
					var w_dif = ($('.box-pic').width() - $(this).width()) * 0.5;

				
					$(this).css("left", (-w_dif).toString() + "px");
					$(this).css("top", (h_dif).toString() + "px");
				}

			});

		});

		setTimeout(function(){ 

		$(".tab_pic").each(function() {

			var title_height = $(".box-title").height();
			var inner_height = $(".box").height() - (title_height + 9);
			$(".box-inner").css("height", inner_height.toString() + "px");
			$(".box-pic").css("height", inner_height.toString() + "px");
			var box_width = $(".box-inner").width();
			var pic_width = $(this).width();
			var pic_height = $(this).height();
			var wid_diff = ((box_width - pic_width) / 2);
			var hit_diff = ((inner_height - pic_height) / 2);
			//var hit_diff = 0;
			$(this).css("left", wid_diff.toString() + "px");
			$(this).css("top", hit_diff.toString() + "px");
			
		});
		
		}, 100);

		$('form.new_tab').submit(function(e) {
			e.preventDefault();
			var valuesToSubmit = $(this).serialize();
			$.ajax({
				type : "POST",
				url : $(this).attr("action"),
				data : valuesToSubmit
			}).success(function() {
				document.getElementById('new_tab').reset();
				$('#newTabModal').modal('hide');
				loadNewTab();
			});
		});

	});

	function loadNewTab() {

		$.ajax({
			url : '/get_new_tab',
			type : "GET",
			dataType : "json",
			success : function(result, textStatus, xhr) {
				// Sets up the data for appending
				var name = result['name'];
				var address = result['address'];
				var picture = result['picture'];
				// Sets up the html string for appending
				var new_data = "<a target='_blank' href='" + address + "' style='display:block'><div class='box new_box_" + name + "'>" + "<div class='box-inner' style='height:167px;width:225px'><div class='box-pic' style='height:167px;width:225px'>"; 
				new_data += "<img class='tab_pic' src='" + picture + "'></img></div><div class='box-title center'>" + name + "</div></div></div></a>";
				// Finds then prepends the new tab
				var $pane = $('div.active').find('.sheet-col');
				$pane.prepend(new_data);
				
				
				//Gives time for picture to load
				setTimeout(function(){ 
    			
    			//JS for better picture placement
				var $box = $('.new_box_' + name);
				var $box_inner = $box.find('.box-inner');
				var $pic = $box.find('.tab_pic');
				var w_dif = ($box.width() - $pic.width()) * 0.5;
				var h_dif = ($box_inner.height() - $pic.height()) * 0.5;
				$pic.css("left", w_dif.toString() + "px");
				$pic.css("top", h_dif.toString() + "px");
    			
    			}, 10);
				
			
				
			}
		});


	}
</script>

<% else %>

<script type="text/javascript">
	$(window).load(function() {
		$('#myModal').modal('show');
	}); 
</script>

<%= provide(:title, 'Home') %>
<div class="container">
	<%= render 'layouts/boxes' %>

	<%= render 'layouts/loginmod'%>
</div>

<% end %>