config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root                  'static_pages#home'
  get     'home'    =>  'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  post    'sheet_change' => 'static_pages#sheet_change'
  get     'get_new_tab'  => 'static_pages#get_new_tab'
  post    'set_screen_size' => 'static_pages#set_screen_size'
  resources :users
  resources :tabs
  resources :sheets

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sheets, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the diges.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forget a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def feed
    Tab.where("user_id = ?", id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user,   only: [:edit, :update, :show, :destroy]
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Bookmark Page #{@user.name}"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end
  
  def edit
    @page_data = page_data
    
  end
  
  private
   
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the ocrrect user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= stylesheet_link_tag "edit_home_box" %>
<%= provide(:title, "Edit links")%>
<%= render 'layouts/edit_options_bar'%>
<% if @page_data != nil %>
<div class="container">
	<% @page_data.each do |key, val| %>
	<div class="row">
		<div class="col-md-3">
			<h2>Tab Name: <%= key.name %></h2>
			<%= link_to "", key, method: :delete, class: "btn btn-danger" %>
		</div>
	
	</div>
	<hr>
	<% unless key.tabs == nil %>
	
	<% key.tabs.each do |aTab| %>
	<div class="row edit-row">
		<div class="col-md-4">
			<%= render aTab if aTab != nil %>
		</div>
		<div class="col-md-6 edit-tab">
			<div class="col-md-3 edit-buttons-section">

				<%= link_to "", aTab, method: :delete, class: "btn btn-danger",
				data: {confirm: "You sure?" } %>
				<br>
				<%= link_to "", edit_tab_path(aTab),  class: "btn btn-default edButton" %>

			</div>

			<div class="col-md-7 tab-info">
				<p>
					Name: <%= aTab.name %>
				</p>
				<p>
					Address: <%= aTab.address %>
				</p>
			</div>

		</div>
	</div>

	<% end %>
	<% end %>
	<% end %>
</div>
<script type="text/javascript">
    $(window).ready(function(){
    	var title_height = $(".box-title").height();
   		var inner_height = $(".box").height() - (title_height + 9);
    	$(".box-inner").css("height", inner_height.toString() + "px");
    	$(".box-pic").css("height", inner_height.toString() + "px");
    	var box_width = $(".box").width();
    	$(".tab_pic").each(function() {
    		
    		var pic_width = $(this).width();
    		var pic_height = $(this).height();
    		var wid_diff = (box_width - pic_width) / 2;
    		var hit_diff = ((inner_height - pic_height) / 2)  ;
    		$(this).css("left", wid_diff.toString() + "px");
    		$(this).css("top", hit_diff.toString() + "px");
    		
    	});

    });
</script>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="center">Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
		
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
			
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
			
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
			
			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name + "'s links")%>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info center">
			<h1>
				<%= @user.name %>	
			</h1>
			<p>
				<%= link_to "delete", @user, method: :delete, data: { confirm: "You sure?"}%>
			</p>
			
			
		</section>
	</aside>
</div>