config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root                  'static_pages#home'
  get     'home'    =>  'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  post    'sheet_change' => 'static_pages#sheet_change'
  get     'get_new_tab'  => 'static_pages#get_new_tab'
  post    'set_screen_size' => 'static_pages#set_screen_size'
  resources :users
  resources :tabs
  resources :sheets

end

app/views/layouts/_boxes.html.erb
<!-- Produce default boxes for the home page without a logged in user -->

<%= stylesheet_link_tag "def_home_box" %>
<% 12.times do %>
	<div class="box">
		<div class="box-inner">
			<div class="box-pic">
			</div>
			<div class="box-title center">
				Title
			</div>	
		</div>
	</div>
<% end %>

app/views/layouts/_edit_options_bar.html.erb
<%= stylesheet_link_tag "edit_home_box" %>
<div class="options">
	<div class="ops-area center">
		
			<button type="button" id="doneEdit" onclick="location.href='<%= root_path %>'" >
				Done
			</button>
		
		
	</div>
	
	
	

	
</div>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-inverse navbar-static-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "Tab Saver", root_path, id: "logo" %>
			</div>

			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<% if logged_in? %>
					<li>
						<%= link_to "Links", root_path %>
					</li>
					<li>
						<%= link_to "Profile", current_user %>
					</li>
					<li>
						<%= link_to "Log out", logout_path, method: "delete" %>
					</li>
					<% else %>
					<li>
						<%= link_to "About", about_path %>
					</li>
					<li>
						<%= link_to "Log in", login_path %>
					</li>
					<li>
						<%= link_to "Sign up", signup_path %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_login.html.erb
<%= stylesheet_link_tag "sessions" %>
<h1 class="center">Log in</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(:session, url: login_path) do |f| %>
		
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
			
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
			
			<%= f.label :remember_me, class: "checkbox inline" do %>
				<%= f.check_box :remember_me %>
				<span>Remember me on this computer</span>
			<% end %>
			
			<%= f.submit "Log in", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/layouts/_loginmod.html.erb
<%= stylesheet_link_tag "sessions" %>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
      <div class="modal-body">
        <%= render 'layouts/login' %>
      </div>
      <div class="modal-footer">
        <%= link_to "About", about_path, class: "btn btn-lrg btn-primary pull-left about-button" %>
        <%= link_to "Sign Up", signup_path, class: "btn btn-lrg btn-primary pull-right signup-button" %>
        
      </div>
    </div>
  </div>
</div>

app/views/layouts/_newTabModal.html.erb
<div class="modal" id="newTabModal" tabindex="-1" role="dialog" aria-labelledby="newTabModalLabel"
			data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
      <div class="modal-body">
        <%= render "layouts/tab_form" %>
      </div>
      <div class="modal-footer">
       
        <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_tab_form.html.erb
<%= form_for(@tab, html: {multipart: true }) do |f| %>
	
	
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :address %>
	<%= f.text_field :address, class: 'form-control' %>
	
	<span class="picture">
		<%= f.label "Upload"%>
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
		<%= f.label "or image Link" %>
		<%= f.text_field :remote_picture_url, class: 'form-control' %>
		
	</span>
	
	<%= f.submit "Add Link", class: "btn btn-primary" %>
	
<% end %> 


<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><%= yield(:title) %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
		
	</head>
	<body>

		<div class="container">
			<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>">
				<%= message %>
			</div>
			<% end %>

		</div>
		<%= render 'layouts/header' %>
		<% mobile_device? ? set_screen_type(1) : set_screen_type(0) %>
		<%= yield %>
	</body>
</html>